apiVersion: v1
kind: Pod
metadata:
  name: fuzzy-test-1
spec:
  schedulerName: fuzzy-scheduler
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.9
---
apiVersion: v1
kind: Pod
metadata:
  name: fuzzy-test-2
spec:
  schedulerName: fuzzy-scheduler
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.9
---
apiVersion: v1
kind: Pod
metadata:
  name: fuzzy-test-3
spec:
  schedulerName: fuzzy-scheduler
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.9
