apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ksense-namespace.yaml
  - ksense-daemonset.yaml
  - fuzzy-webhook-service.yaml
  - fuzzy-webhook-configuration.yaml
  - fuzzy-scheduler.yaml
